const PLACE_CATEGORIES = {
  cafe: { label: "คาเฟ่", googleType: "cafe", query: "คาเฟ่" },
  concert: { label: "คอนเสิร์ต", query: "คอนเสิร์ต" },
  amusement: { label: "สวนสนุก", googleType: "amusement_park", query: "สวนสนุก" },
  restaurant: { label: "ร้านอาหาร", googleType: "restaurant", query: "ร้านอาหาร" },
  entertainment: { label: "สถานบันเทิง", query: "สถานบันเทิง" },
  camp: { label: "แคมป์", googleType: "campground", query: "แคมป์" },
  golf: { label: "สนามกอล์ฟ", googleType: "golf_course", query: "สนามกอล์ฟ" },
  river: { label: "ริมแม่น้ำ", query: "ริมน้ำ" },
  park: { label: "สวนสาธารณะ", googleType: "park", query: "สวนสาธารณะ" },
  temple: { label: "วัด", googleType: "place_of_worship", query: "วัด" },
  forest: { label: "ป่าเขา", query: "ป่าเขา" },
  viewpoint: { label: "จุดชมวิว", query: "จุดชมวิว" },
  beach: { label: "ทะเล", query: "ทะเล" },
  exhibition: { label: "นิทรรศการ", query: "นิทรรศการ" },
  workshop: { label: "workshop", query: "workshop" },
  event: { label: "งาน Event", query: "Event" },
  boardgame: { label: "ร้านบอร์ดเกม", query: "ร้านบอร์ดเกม" },
  mall: { label: "ห้างสรรพสินค้า", googleType: "shopping_mall", query: "ห้างสรรพสินค้า" },
  spa: { label: "สปา", googleType: "spa", query: "สปา" },
  onsen: { label: "ออนเซน", query: "ออนเซน" },
  resort: { label: "ที่พักท่ามกลางธรรมชาติ", query: "ที่พักท่ามกลางธรรมชาติ" },
  gaming: { label: "ร้านเกม", query: "ร้านเกม" },
  sports: { label: "สนามกีฬา", query: "สนามกีฬา" },
  hiking: { label: "เดินป่า/ภูเขา", query: "เดินป่า" },
  gym: { label: "ยิม", googleType: "gym", query: "ยิม" },
  bar: { label: "บาร์", googleType: "bar", query: "บาร์" },
  cinema: { label: "โรงภาพยนตร์", googleType: "movie_theater", query: "โรงภาพยนตร์" },
  karaoke: { label: "คาราโอเกะ", query: "คาราโอเกะ" },
  fitness: { label: "ฟิตเนส", googleType: "gym", query: "ฟิตเนส" },
  shooting: { label: "สนามยิงปืน", query: "สนามยิงปืน" },
};

module.exports = { PLACE_CATEGORIES };